"""
=========================================================
KAI Smart Money AI

Description:
------------
Defines the core data models used throughout KAI.

These models represent market data and analysis results.
They do not perform calculations or contain business logic.

Author: Vincent Chimezirim
Version: 1.0.0
=========================================================
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime

from data.enums import (
    ConfidenceLevel,
    FairValueGapType,
    LiquidityType,
    MarketSession,
    OrderBlockType,
    PriceZone,
    StructureEvent,
    SwingType,
    Trend,
)

#------------------------------------------------
# Market Models
#------------------------------------------------

@dataclass(frozen=True, slots=True)
class Candle:
    """Represents a single market candle."""

    symbol: str
    timeframe: str 
    time: datetime
    open: float
    high: float
    low: float
    close: float
    tick_volume: int
    spread: int
    real_volume: int

@dataclass(frozen=True, slots=True)
class MarketData:
    """Represents a collection of candles  
    for one symbol and timeframe.
    """

    symbol: str
    timeframe: str
    Candles: list[Candle]


#--------------------------------------------------
# Analysis Models
#--------------------------------------------------

@dataclass(frozen=True, slots=True)
class SwingPoint:
    """Represent a validated swing high or swing low"""

    index: int
    time: datetime
    price: float
    swing_type: SwingType
    strength: int


@dataclass(frozen=True, slots=True)
class StructureAnalysis:
    """Market structure analysis."""

    trend: Trend
    event: StructureEvent
    break_price: float | None
    confidence: ConfidenceLevel
    explanation: str

@dataclass(frozen=True, slots=True)
class LiquidityLevel:
    liquidity_type: LiquidityType
    price: float
    time: datetime
    touched: bool


@dataclass(frozen=True, slots=True)
class FairValueGap:
    """Fair Value Gap."""

    gap_type: FairValueGapType
    high: float
    low: float
    filled: bool


@dataclass(frozen=True, slots=True)
class OrderBlock:
    """Institutional Order Block"""

    block_type: OrderBlockType
    high: float
    low: float
    mitigated: bool


#---------------------------------------------
# Final Analysis Model
#-------------------------------------------

@dataclass(frozen=True, slots=True)
class MarketAnalysis:
    """Complete market analysis generated by KAI.
    """

    synbol: str
    timeframe: str
    trend: Trend
    session: MarketSession
    price_zone: PriceZone
    confidence: ConfidenceLevel
    swings: list[SwingPoint] = field(default_factory=list)
    liquidity: list[LiquidityLevel] = field(default_factory=list)
    fair_value_gaps: list[FairValueGap] = field(default_factory=list)
    order_blocks: list[OrderBlock] = field(default_factory=list)

    explanation: str = "" 