"""
=========================================================
KAI Smart Money AI
File: fair_value_gap.py

Description
-----------
Represents a Fair Value Gap (FVG).

Generated by the Fair Value Gap Engine. and used by
Confluence, AI Reasoning, Strategy,
Risk Management and Visualization.

Author:
Vincent Chimezirim
=========================================================
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Literal


@dataclass
class FairValueGap:
    """
    Represents a Fair Value Gap.
    """

    timestamp: datetime

    index: int

    high: float

    low: float

    direction: Literal["BULLISH", "BEARISH"]

    filled: bool = False

    consequent_encroachment: bool = False

    strength: float = 0.0

    def __post_init__(self) -> None:
        """
        Validate Fair Value Gap values.
        """

        if self.index < 0:
            raise ValueError(
                "Index cannot be negative."
            )

        if self.high <= self.low:
            raise ValueError(
                "High must be greater than Low."
            )

        if self.strength < 0:
            raise ValueError(
                "Strength cannot be negative."
            )

    @property
    def midpoint(self) -> float:
        """
        Returns the Consequent Encroachment (50%)
        of the Fair Value Gap.
        """
        return (self.high + self.low) / 2

    @property
    def height(self) -> float:
        """
        Returns the size of the Fair Value Gap.
        """
        return self.high - self.low

    @property
    def is_bullish(self) -> bool:
        """
        Returns True if Bullish FVG.
        """
        return self.type == "BULLISH"

    @property
    def is_bearish(self) -> bool:
        """
        Returns True if Bearish FVG.
        """
        return self.type == "BEARISH"

    @property
    def is_active(self) -> bool:
        """
        Returns True if the FVG has not
        been completely filled.
        """
        return not self.filled