"""
=========================================================
KAI Smart Money AI
File: liquidity.py

Description
-----------
Represents a Smart Money liquidity zone.

Generated by the Smart Money Engine and used by
Order Blocks, Fair Value Gaps, Confluence,
AI Reasoning and Strategy.

Author:
Vincent Chimezirim
=========================================================
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Literal


@dataclass
class Liquidity:
    """
    Represents a liquidity zone.
    """

    timestamp: datetime

    index: int

    price: float

    direction: Literal[
        "BUY_SIDE",
        "SELL_SIDE",
        "EQUAL_HIGH",
        "EQUAL_LOW",
        "TRIPLE_TOP",
        "TRIPLE_BOTTOM",
    ]

    touches: int = 2

    strength: float = 0.0

    swept: bool = False

    grabbed: bool = False

    def __post_init__(self):
        """
        Validate liquidity data.
        """

        if self.index < 0:
            raise ValueError(
                "Index cannot be negative."
            )

        if self.price <= 0:
            raise ValueError(
                "Price must be greater than zero."
            )

        if self.touches < 2:
            raise ValueError(
                "Liquidity requires at least two touches."
            )

        if self.strength < 0:
            raise ValueError(
                "Strength cannot be negative."
            )

    @property
    def is_buy_side(self) -> bool:
        """Returns True if buy-side liquidity."""
        return self.type == "BUY_SIDE"

    @property
    def is_sell_side(self) -> bool:
        """Returns True if sell-side liquidity."""
        return self.type == "SELL_SIDE"

    @property
    def is_equal_high(self) -> bool:
        """Returns True if equal highs."""
        return self.type == "EQUAL_HIGH"

    @property
    def is_equal_low(self) -> bool:
        """Returns True if equal lows."""
        return self.type == "EQUAL_LOW"

    @property
    def is_triple_top(self) -> bool:
        """Returns True if triple top."""
        return self.type == "TRIPLE_TOP"

    @property
    def is_triple_bottom(self) -> bool:
        """Returns True if triple bottom."""
        return self.type == "TRIPLE_BOTTOM"

    @property
    def is_taken(self) -> bool:
        """
        Returns True if liquidity has been taken.

        Liquidity is considered taken when it has
        either been swept or grabbed.
        """
        return self.swept or self.grabbed