"""
=========================================================
KAI Smart Money AI
File: order_block.py

Description
-----------
Represents an Institutional Order Block.

Generated by the Smart Money Engine and used by
Confluence, AI Reasoning, Risk Management,
Strategy and Visualization.

Author:
Vincent Chimezirim
=========================================================
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Literal


@dataclass
class OrderBlock:
    """
    Represents an Institutional Order Block.
    """

    timestamp: datetime

    index: int

    high: float

    low: float

    direction: Literal["BULLISH", "BEARISH"]

    fresh: bool = True

    mitigated: bool = False

    refined: bool = False

    nested: bool = False

    strength: float = 0.0

    def __post_init__(self):
        """
        Validate Order Block values.
        """

        if self.index < 0:
            raise ValueError(
                "Index cannot be negative."
            )

        if self.high <= self.low:
            raise ValueError(
                "High must be greater than Low."
            )

        if self.strength < 0:
            raise ValueError(
                "Strength cannot be negative."
            )

    @property
    def midpoint(self) -> float:
        """
        Returns the midpoint of the Order Block.
        """
        return (self.high + self.low) / 2

    @property
    def height(self) -> float:
        """
        Returns the size of the Order Block.
        """
        return self.high - self.low

    @property
    def is_bullish(self) -> bool:
        """
        Returns True if Bullish Order Block.
        """
        return self.type == "BULLISH"

    @property
    def is_bearish(self) -> bool:
        """
        Returns True if Bearish Order Block.
        """
        return self.type == "BEARISH"

    @property
    def is_active(self) -> bool:
        """
        Returns True if the Order Block
        is still valid for trading.

        An Order Block is considered active
        if it has not been mitigated.
        """
        return not self.mitigated